name: PyPI publish
description: "Publish built distributions to PyPI via Trusted Publishing"

inputs:
  dist_dir:
    description: "Directory containing built distributions (e.g. filesystem/dist)"
    required: true

runs:
  using: composite
  steps:
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ${{ inputs.dist_dir }}
        # Avoid GitHub artifact attestations for now.
        # With attestations enabled, the action may attempt to interact with GHCR
        # (e.g. pulling/pushing provenance subjects), which can fail if the image
        # isn't published or permissions aren't configured.
        attestations: false
